name: Oracle ARM Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create Key File
        env:
          RAW_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY_FILENAME }}
        run: |
          echo "$RAW_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

      - name: Run OCI Bot
        run: |
          # Limpieza automatica de comillas, comillas simples y retornos de carro
          export OCI_REGION=$(echo "${{ secrets.OCI_REGION }}" | tr -d '"'\''\r ')
          export OCI_USER_ID=$(echo "${{ secrets.OCI_USER_ID }}" | tr -d '"'\''\r ')
          export OCI_TENANCY_ID=$(echo "${{ secrets.OCI_TENANCY_ID }}" | tr -d '"'\''\r ')
          export OCI_KEY_FINGERPRINT=$(echo "${{ secrets.OCI_KEY_FINGERPRINT }}" | tr -d '"'\''\r ')
          export OCI_SUBNET_ID=$(echo "${{ secrets.OCI_SUBNET_ID }}" | tr -d '"'\''\r ')
          export OCI_OCPUS=$(echo "${{ secrets.OCI_OCPUS }}" | tr -d '"'\''\r ')
          export OCI_MEMORY_IN_GBS=$(echo "${{ secrets.OCI_MEMORY_IN_GBS }}" | tr -d '"'\''\r ')
          export OCI_SHAPE=$(echo "${{ secrets.OCI_SHAPE }}" | tr -d '"'\''\r ')
          export OCI_MAX_INSTANCES=$(echo "${{ secrets.OCI_MAX_INSTANCES }}" | tr -d '"'\''\r ')
          export OCI_PRIVATE_KEY_FILENAME="key.pem"
          export OCI_SSH_PUBLIC_KEY="${{ secrets.OCI_SSH_PUBLIC_KEY }}"
          export TELEGRAM_USER_ID="${{ secrets.TELEGRAM_USER_ID }}"
          export TELEGRAM_BOT_API_KEY="${{ secrets.TELEGRAM_BOT_API_KEY }}"
          
          php index.php
